// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB078mL11DxFkO0beJ-J0TXkrT7PJ5kLFo',
    appId: '1:448091609524:web:d535fbd5488b1c1f0e3ae1',
    messagingSenderId: '448091609524',
    projectId: 'studybuddy-db',
    authDomain: 'studybuddy-db.firebaseapp.com',
    storageBucket: 'studybuddy-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAul2yI0UMLHcbHOTe9wxIRl7HCdOxBc_c',
    appId: '1:448091609524:android:22fa480bc6017cd70e3ae1',
    messagingSenderId: '448091609524',
    projectId: 'studybuddy-db',
    storageBucket: 'studybuddy-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtqC4LBgv9lYgtUfeEkGY_8vW1uc5tQPY',
    appId: '1:448091609524:ios:7a9907171322beb80e3ae1',
    messagingSenderId: '448091609524',
    projectId: 'studybuddy-db',
    storageBucket: 'studybuddy-db.firebasestorage.app',
    androidClientId: '448091609524-058qapr70lrprfrli31eohcbr6ao4i8f.apps.googleusercontent.com',
    iosClientId: '448091609524-615kdepkf76egpqjno68kojhp3t9hts6.apps.googleusercontent.com',
    iosBundleId: 'com.example.studybuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtqC4LBgv9lYgtUfeEkGY_8vW1uc5tQPY',
    appId: '1:448091609524:ios:7a9907171322beb80e3ae1',
    messagingSenderId: '448091609524',
    projectId: 'studybuddy-db',
    storageBucket: 'studybuddy-db.firebasestorage.app',
    androidClientId: '448091609524-058qapr70lrprfrli31eohcbr6ao4i8f.apps.googleusercontent.com',
    iosClientId: '448091609524-615kdepkf76egpqjno68kojhp3t9hts6.apps.googleusercontent.com',
    iosBundleId: 'com.example.studybuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB078mL11DxFkO0beJ-J0TXkrT7PJ5kLFo',
    appId: '1:448091609524:web:32e8f3438f8e47da0e3ae1',
    messagingSenderId: '448091609524',
    projectId: 'studybuddy-db',
    authDomain: 'studybuddy-db.firebaseapp.com',
    storageBucket: 'studybuddy-db.firebasestorage.app',
  );
}
